version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'movie-dev'
      MYSQL_USER: 'usr-movie'
      MYSQL_PASSWORD: 'pwd-movie'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  mongo-container:
    image: mongo
    container_name: mongo-catalog
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: 'catalog'
      MONGO_INITDB_ROOT_USERNAME: 'usr-catalog'
      MONGO_INITDB_ROOT_PASSWORD: 'pwd-catalog'
    ports:
      - '27018:27017'
      - '2018'

    volumes:
      - ./mongo-init-catalog.js:/docker-entrypoint-initdb.d/mongo-init-catalog.js:ro



  mongo-series:
    image: mongo
    container_name: mongo-series
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: 'series'
      MONGO_INITDB_ROOT_USERNAME: 'usr-serie'
      MONGO_INITDB_ROOT_PASSWORD: 'pwd-serie'
    ports:
      - '27019:27017'
    expose:
      - '27019'

    volumes:
      - ./mongo-init-series.js:/docker-entrypoint-initdb.d/mongo-init-series.js:ro

  zipkin-server-container:
    image: openzipkin/zipkin-slim
    container_name: zipkin-server-container
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    expose:
      - 9411
    depends_on:
      - storage-aux-container
  storage-aux-container:
    image: busybox:1.31.0
    container_name: storage-aux-container
  rabbitmq-container:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 15672
      - 5672












   