version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'movie-dev'
      MYSQL_USER: 'usr-movie'
      MYSQL_PASSWORD: 'pwd-movie'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  zipkin-server-container:
    image: openzipkin/zipkin-slim
    container_name: zipkin-server-container
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    expose:
      - 9411
    depends_on:
      - storage-aux-container
  storage-aux-container:
    image: busybox:1.31.0
    container_name: storage-aux-container
  rabbitmq-container:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 15672
      - 5672
   